name: Flutter Pipeline

on:
  pull_request:
    branches: [develop]
jobs:
  lint_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
      - run: flutter pub get
      - run: flutter analyze
      - run: flutter test

  build_ios:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
      - run: flutter pub get
      - run: flutter build ios --no-codesign

  build_apk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable" # 'dev', 'alpha', default to: 'stable'
      - run: flutter pub get
      - run: flutter build apk
